### ISSUE TITLE
[ Bug ] Showing one Inhibitor Side, shows both instad

### ISSUE THREAD

**Issue by JoanJuan10** [RCVolus/league-prod-toolkit#252]
**Describe the bug**
Whenever I use Show Red Inhib or Show Blue inhib, instead it inserts the "Both" class to show both inhibitor sides.

**To Reproduce**
Show one side of inhibs
**Expected behavior**
Only one side is shown in whole window

**Screenshots**
![Image](https://i.imgur.com/nE8ETey.png)

**System:**

- OS: Windows 10
- Node: 8.13.2
- Prod Tool Version: 1.4.1
- Observer Tool Version: 5.0.0
- Streaming Software & Version: OBS
- Browser: Chrome

**Additional context**
I tried using the red and blue class and whenever modified, it instanty changes back to both
![Image](https://i.imgur.com/6bPHhhY.png)

And then:
![Image](https://i.imgur.com/MvAtLQ7.png)

**Comment by sdomi4** [comment]
I am unable to reproduce this on my side.
Have you made any modifications to the ingame module in code/through a theme?
Could you double-check your node version? (I assume what you listed is the npm version but just making sure)

**Comment by JoanJuan10** [comment]
Here is the theme I use:
```scss
:root {
    --blue-team: #029ef7;
    --blue-team-dark: hsl(202, 98%, 40%);
    --blue: #029ef7;
    --blue-dark: hsl(202, 98%, 40%);
    --red-team: #ff5a64;
    --red: #ff5a64;
    --red-dark: hsl(356, 100%, 59%);
    --red-team-dark: hsl(356, 100%, 59%);
    --accent-color: #d8ef5e;
    --text-color: #fafafa;
    --background-color: #051c2c;
    --primary-font-family: monospace;
    --secondary-font-family: sans-serif;
    --logo-path: url(/pages/op-themeing/active/logo.png);
}
.sb-blue {
  background: linear-gradient(90deg, var(--blue-team-dark) 0%, var(--background-color) 26%, var(--background-color) 100%)!important;

  .sb-team-info {
    color: var(--blue-team);
  }
  .sb-stat {
    color: var(--blue-dark)!important;
  }
}
.sb-red {
  background: linear-gradient(90deg, var(--background-color) 0%, var(--background-color) 74%, var(--red-team-dark) 100%)!important;

  .sb-team-info {
    color: var(--red-team);
    padding: 5px 20px 0 0px!important;
  }
  .sb-stat {
    color: var(--red-dark)!important;
  }
}
.sb-kills-blue {
  color: var(--blue-dark)!important;
  margin-bottom: 5px;
}
.sb-kills-red {
  color: var(--red-dark)!important;
  margin-bottom: 5px;
}

.sb-kills {
  background: var(--background-color)!important;
}

.sb-team {
  font-size: 20px;
}

.sb-red.power-play {
  padding-left: 10px!important;
}
.sb-blue.power-play  {
  padding-right: 10px!important;
}
.power-play.baron {
  background: rgb(101,0,246)!important;
  background: linear-gradient(90deg, rgba(101,0,246,1) 0%, rgba(121,9,91,1) 52%, rgba(169,0,255,1) 100%)!important;
}

.power-play {
    
    .timer {
        font-size: 25px;
    }
    .pp-box {
      h1 {
        font-size: 25px;
        letter-spacing: 0px!important;
      }
      h3 {
        font-size: 25px;
      }
    }
}

```
Sorry about the node version, it seems it has recently updated: v16.15.1
