### ISSUE TITLE
I'm having problems customizing certain things. I just have a few questions. [ Question ]

### ISSUE THREAD

**Issue by EagleLOL** [RCVolus/league-prod-toolkit#264]
Hello. I'm thinking about using this program for a tournament. I'm wondering how I can change certain things. To be exact : 
1- Certain words that appear in the in game and end game overlays. I'm trying to change the words to my target audience's language.
2- Backgrounds that appear in the ingame overlay for example the dragon and baron anouncements have a basic blue and red background. Same for the scoreboard as well. Can use backgrounds for these or is it only possible to use colors?
3- How do I change fonts? Can I use different fonts for different scenes and overlays. Can I change their size?

**Comment by sdomi4** [comment]
1 - At the moment, the only way to change text is by directly editing the source. The HTML files you need to edit are usually located in `...\prod-toolkit\modules\[module]\frontend\`. Note that updating the toolkit will overwrite any manual changes you make. We are planning to add localization, but don't expect anything soon.

2/3 - You can change backgrounds and fonts using [theming](https://github.com/RCVolus/league-prod-toolkit/wiki/3.-Customisation).

To change backgrounds, you can set a `background-image` for the elements you wish to change, for example the scoreboard, where `background.jpg` is placed in the theme folder:
```scss
.scoreboard {
  background-image: url(/pages/op-plugin-theming/active/background.jpg);
}
```
If you are changing the scoreboard background to be an image, you might want to hide the color background:
```scss
.sb-team.sb-blue, .sb-team.sb-red, .sb-kills, .sb-time {
  background: none;
  box-shadow: none;
}
```

To change fonts / font sizes individually rather than globally in the theme, set them on the element in question, for example the team tags ingame:
```scss
.sb-tag {
  font-family: 'Courier New', Courier, monospace;
  font-size: 48px;
}
```
